# example workflow for Coverity on Polaris
name: coverity-on-polaris
on:
  push:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  coverity-on-polaris:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Check Env
      run: |
        echo "pwd : $(pwd)"
        echo "ls :"
        ls -al
        echo "github.workspace = ${{ github.workspace }}"
        ls -al ${{ github.workspace }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: microsoft
        cache: maven
    - name: Coverity on Polaris Scan
      env:
        POLARIS_SERVER_URL: ${{ vars.POLARIS_SERVER_URL }}
        POLARIS_ACCESS_TOKEN: ${{ secrets.POLARIS_ACCESS_TOKEN }}
      run: |
        curl -fLsS -o polaris.zip $POLARIS_SERVER_URL/api/tools/polaris_cli-linux64.zip
        unzip -d ${{ runner.temp }} -jo polaris.zip && rm -f polaris.zip
        # Auto Capture 
        # ${{ runner.temp }}/polaris --co project.name=chuckaude-${{ github.event.repository.name }} analyze -w
        
        # Auto Capture with specific coverity-custom.yaml, not using coverity.yaml
        # ${{ runner.temp }}/polaris -c polaris-custom.yml --co project.name=chuckaude-${{ github.event.repository.name }} analyze -w

        # Build Capture 
        # ${{ runner.temp }}/polaris -c polaris-build.yml --co project.name=chuckaude-${{ github.event.repository.name }}  analyze -w --coverity-ignore-capture-failure

        # Buildless Capture 
        # ${{ runner.temp }}/polaris -c polaris-buildless.yml --co project.name=chuckaude-${{ github.event.repository.name }}  analyze -w --coverity-ignore-capture-failure
        
        # FileSystem Capture 
        ${{ runner.temp }}/polaris -c polaris-filesystem.yml --co project.name=chuckaude-${{ github.event.repository.name }}  analyze -w --coverity-ignore-capture-failure

        # Build & Buildless Capture 
        # ${{ runner.temp }}/polaris -c polaris-build-buildless.yml --co project.name=chuckaude-${{ github.event.repository.name }}  analyze -w --coverity-ignore-capture-failure

        # Build & FileSystem Capture 
        # ${{ runner.temp }}/polaris -c polaris-build-filesystem.yml --co project.name=chuckaude-${{ github.event.repository.name }}  analyze -w --coverity-ignore-capture-failure

    - name: Save Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: polaris-cli-logs
        path: ${{ github.workspace }}/.synopsys/
        # path: .synopsys/
